name: Fly
main: Nerahikada\Fly\Main
version: 1.0.0
api: 3.0.0-ALPHA11
load: POSTWORLD
author: ねらひかだ
description: 飛べます！
website: https://github.com/Nerahikada/Fly

commands:
  fly:
    description: 飛行を切り替えます
    usage: /fly